apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: admin-server
  ports:
  - protocol: TCP
    port: {{ .Values.adminServer.port }}
    targetPort: {{ .Values.adminServer.port }}
    nodePort: {{ .Values.adminServer.nodePort }}
  type: NodePort