apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: customers-service
  ports:
  - protocol: TCP
    port: {{ .Values.customersService.port }}
    targetPort: {{ .Values.customersService.port }}
    nodePort: {{ .Values.customersService.nodePort }}
  type: NodePort