apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      initContainers:
      - name: wait-for-discovery-server
        image: busybox:1.36
        command:
        - sh
        - -c
        - "until nc -z discovery-server 8761; do echo 'Waiting for discovery-server...'; sleep 5; done"
      containers:
      - name: customers-service
        image: "{{ .Values.customersService.repository }}:{{ .Values.customersService.tag }}"
        ports:
        - containerPort: {{ .Values.customersService.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
        - name: SPRING_LOGGING_FILE_NAME
          value: ""
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: customers-service
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
        - name: EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS
          value: "10"
        - name: EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS
          value: "10"
        - name: EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS
          value: "10"