apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: "{{ .Values.discoveryServer.repository }}:{{ .Values.discoveryServer.tag }}"
        ports:
        - containerPort: {{ .Values.discoveryServer.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
        - name: SPRING_LOGGING_FILE_NAME
          value: ""
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: discovery-server
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
        - name: EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS
          value: "10"
        - name: EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS
          value: "10"
        - name: EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS
          value: "10"
        - name: EUREKA_SERVER_PEER_NODE_READ_TIMEOUT_MS
          value: "10000"
