apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: discovery-server
  ports:
  - protocol: TCP
    port: {{ .Values.discoveryServer.port }}
    targetPort: {{ .Values.discoveryServer.port }}
    nodePort: {{ .Values.discoveryServer.nodePort }}
  type: NodePort