apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: genai-service
  ports:
  - protocol: TCP
    port: {{ .Values.genaiService.port }}
    targetPort: {{ .Values.genaiService.port }}
    nodePort: {{ .Values.genaiService.nodePort }}
  type: NodePort