apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tracing-server
  ports:
  - protocol: TCP
    port: {{ .Values.tracingServer.port }}
    targetPort: {{ .Values.tracingServer.port }}
    nodePort: {{ .Values.tracingServer.nodePort }}
  type: NodePort