apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: visits-service
  ports:
  - protocol: TCP
    port: {{ .Values.visitsService.port }}
    targetPort: {{ .Values.visitsService.port }}
    nodePort: {{ .Values.visitsService.nodePort }}
  type: NodePort