# Release tag (for dev deployment)
releaseTag: latest

# Service configurations
adminServer:
  repository: pmhanh/spring-petclinic-admin-server
  tag: latest
  port: 9090
  nodePort: 32090

tracingServer:
  repository: openzipkin/zipkin
  tag: latest
  port: 9411
  nodePort: 32100

apiGateway:
  repository: pmhanh/spring-petclinic-api-gateway
  tag: latest
  port: 8080
  nodePort: 32080

configServer:
  repository: pmhanh/spring-petclinic-config-server
  tag: latest
  port: 8888
  nodePort: 32120

customersService:
  repository: pmhanh/spring-petclinic-customers-service
  tag: latest
  port: 8081
  nodePort: 32130

discoveryServer:
  repository: pmhanh/spring-petclinic-discovery-server
  tag: latest
  port: 8761
  nodePort: 32110

genaiService:
  repository: pmhanh/spring-petclinic-genai-service
  tag: latest
  port: 8084
  nodePort: 32140

vetsService:
  repository: pmhanh/spring-petclinic-vets-service
  tag: latest
  port: 8083
  nodePort: 32150

visitsService:
  repository: pmhanh/spring-petclinic-visits-service
  tag: latest
  port: 8082
  nodePort: 32160